@startuml
/'
This diagram, for Day 59, was created and then generated into a png file using the PlantUML Extension for VS Code.
CTRL + SHIFT + P --> PlantUML: Generate URL for Current Diagram.
The plantuml server currently being used to generate UML diagrams on-the-fly is https://www.plantuml.com/plantuml.
'/
!define AzurePuml https://raw.githubusercontent.com/RicardoNiepel/Azure-PlantUML/master/dist
!includeurl https://raw.githubusercontent.com/RicardoNiepel/Azure-PlantUML/release/2-1/dist/AzureCommon.puml
!includeurl AzurePuml/AzureCommon.puml
!includeurl AzurePuml/Compute/AzureFunction.puml
!includeurl AzurePuml/Containers/all.puml
!includeurl AzurePuml/Databases/AzureCosmosDb.puml
!includeurl AzurePuml/Management/all.puml
!includeurl AzurePuml/Security/AzureKeyVault.puml

skinparam BackgroundColor Azure

title Subscription Management using Service Principals

actor "Sauron" as Sauron #Red
agent "mgmt-service-principal" as MgmtServicePrincipal #Turquoise
agent "rg-1-service-principal" as rg1ServicePrincipal #Turquoise
agent "rg-2-service-principal" as rg2ServicePrincipal #Turquoise
agent "rg-3-service-principal" as rg3ServicePrincipal #Turquoise
agent "Azure DevOps" as AzDo #Turquoise

AzureResourceGroups(RG1, "k8s-elves", "K8s Cluster Dev")
AzureResourceGroups(RG2, "k8s-dwarfs", "K8s Cluster Stg")
AzureResourceGroups(RG3, "k8s-men", "K8s Cluster Prod")

Sauron --> MgmtServicePrincipal : Step 1: Deploy Mgmt Service Principal
MgmtServicePrincipal --> AzDo : Step 2: Add Service Connection

AzDo --> rg1ServicePrincipal
AzDo --> rg2ServicePrincipal
AzDo --> rg3ServicePrincipal

rg1ServicePrincipal --> RG1
rg2ServicePrincipal --> RG2
rg3ServicePrincipal --> RG3

@enduml$